query QUEERY_ARTICLE_ALL {
  articles {
    totalCount
    totalPage
    pageSize
    edges {
      node {
        id
        title
        summary
      }
    }
  }
}
query QUEERY_ARTICLE_CHANNEL_ALL {
  channels: articleChannels {
    id
    icon
    name
    path
    index
    level
    cover
    parent {
      id
    }
  }
}

query QUEERY_ARTICLE_CHANNEL($id: ID!) {
  channel: articleChannel(id: $id) {
    id
    icon
    name
    cover
    path
    index
    level
    parent {
      id
    }
  }
}

mutation MUTATE_CREATE_ARTICLE($input: ArticleCreateInput!) {
  article: createArticle(input: $input) {
    id
    title
    status
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation MUTATE_UPDATE_ARTICLE($id: ID!, $input: ArticleUpdateInput!) {
  article: updateArticle(id: $id, input: $input) {
    id
    title
    status
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}
