query module($id: ID!) {
  module(id: $id) {
    id
    code
    name
    picture
    description
  }
}

query modules($filter: ModuleFilter, $limit: Int) {
  modules(filter: $filter, limit: $limit) {
    id
    name
    code
    picture
    pictureUrl: picture(format: url)
    description
  }
}

mutation createModule($input: ModuleCreateInput!) {
  createModule(input: $input) {
    id
    code
    name
    picture
    description
  }
}

mutation updateModule($id: ID!, $input: ModuleUpdateInput!) {
  updateModule(id: $id, input: $input) {
    id
    code
    name
    picture
    description
  }
}

mutation deleteModule($id: ID!) {
  deleteModule(id: $id)
}

mutation deleteManyModules($ids: [ID!]!) {
  deleteManyModules(ids: $ids)
}
