query schema($module: ID!) {
  models(module: $module, filter: { type: ENTITY }) {
    id
    code
    name
    description
  }
}

query model($id: ID) {
  model(id: $id) {
    id
    code
    name
    description
    fields {
      id
      code
      system
      type {
        id
        name
        family
        description
        graphQLType
      }
      name
      description
      metadata {
        databaseColumnName
      }
    }
  }
}

query modelFiledTypes {
  filedTypes: modelFiledTypes {
    id
    name
    description
    family
  }
}

query modelFields($model: ID!, $filter: ModelFieldFilter, $limit: Int) {
  listFields: modelFields(model: $model, filter: $filter, limit: $limit) {
    id
    name
    description
  }
}

mutation createModel($input: ModelCreateInput!) {
  createModel(input: $input) {
    id
    name
  }
}

mutation addModelField($modelId: ID!, $input: ModelFieldInput!) {
  addModelField(modelId: $modelId, input: $input) {
    id
    name
  }
}

mutation removeModelField($modelId: ID!, $fieldId: ID!) {
  removeModelField(modelId: $modelId, fieldId: $fieldId)
}
