query schema($module: ID!) {
  models(module: $module, filter: { type: ENTITY }) {
    id
    code
    name
    description
  }
}

query models($moduleId: ID!, $filter: ModelFilter, $limit: Int) {
  models(module: $moduleId, filter: $filter, limit: $limit) {
    id
  }
}

query model($id: ID) {
  model(id: $id) {
    id
    code
    name
    description
    fields {
      id
      code
      system
      required
      index
      type {
        id
        name
        family
        description
        graphQLType
      }
      name
      description
      metadata {
        databaseColumnName
      }
    }
    metadata {
      databaseTableName
    }
  }
}

query modelFiledTypes {
  filedTypes: modelFiledTypes {
    id
    name
    description
    family
  }
}

query modelFields($model: ID!, $filter: ModelFieldFilter, $limit: Int) {
  listFields: modelFields(model: $model, filter: $filter, limit: $limit) {
    id
    name
    description
  }
}

mutation createModel($input: ModelCreateInput!) {
  createModel(input: $input) {
    id
    name
  }
}

mutation updateModel($id: ID!, $input: ModelUpdateInput!) {
  updateModel(id: $id, input: $input) {
    id
    name
  }
}

mutation deleteModel($id: ID!) {
  deleteModel(id: $id)
}

mutation addModelField($modelId: ID!, $input: ModelFieldInput!) {
  addModelField(modelId: $modelId, input: $input) {
    id
    code
    system
    type {
      id
      name
      family
      description
      graphQLType
    }
    name
    description
    metadata {
      databaseColumnName
    }
  }
}

mutation updateModelField($modelId: ID!, $fieldId: ID!, $input: ModelFieldInput!) {
  updateModelField(modelId: $modelId, fieldId: $fieldId, input: $input) {
    id
    code
    system
    type {
      id
      name
      family
      description
      graphQLType
    }
    name
    description
    metadata {
      databaseColumnName
    }
  }
}

mutation removeModelField($modelId: ID!, $fieldId: ID!) {
  removeModelField(modelId: $modelId, fieldId: $fieldId)
}
