query QUEERY_ARTICLE_ALL($filter: ArticleFilter, $page: Int, $pageSize: Int) {
  articles(filter: $filter, page: $page, pageSize: $pageSize) {
    total: totalCount
    current: currentPage
    totalPage
    pageSize
    edges {
      node {
        id
        title
        summary
        authors {
          id
          name
        }
        createdBy
        createdAt
        publishedAt
        status
      }
    }
  }
}

query QUEERY_ARTICLE_CHANNEL_ALL {
  channels: articleChannels {
    id
    icon
    name
    fullName
    path
    index
    level
    cover
    parent {
      id
    }
  }
}

query QUEERY_ARTICLE_CHANNEL($id: ID!) {
  channel: articleChannel(id: $id) {
    id
    icon
    name
    cover
    path
    index
    level
    parent {
      id
    }
  }
}

mutation MUTATE_CREATE_ARTICLE($input: ArticleCreateInput!) {
  article: createArticle(input: $input) {
    id
    title
    status
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation MUTATE_UPDATE_ARTICLE($id: ID!, $input: ArticleUpdateInput!) {
  article: updateArticle(id: $id, input: $input) {
    id
    title
    status
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation MUTATE_DELETE_ARTICLE($id: ID!) {
  deleteArticle(id: $id)
}

mutation MUTATE_DELETE_MANY_ARTICLES($ids: [ID]!) {
  deleteManyArticles(ids: $ids)
}

query QUERY_ARTICLE($id: ID!) {
  article(id: $id) {
    id
    title
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation MUTATE_CREATE_ARTICLE_CHANNEL($input: ArticleChannelCreateInput!) {
  createArticleChannel(input: $input) {
    id
  }
}
