query articleStoreTemplates {
  articleStoreTemplates {
    id
    name
  }
}

query articles($filter: ArticleFilter, $page: Int, $pageSize: Int) {
  articles(filter: $filter, page: $page, pageSize: $pageSize) {
    total: totalCount
    current: currentPage
    totalPage
    pageSize
    edges {
      node {
        id
        title
        summary
        authors {
          id
          name
        }
        channels {
          id
          fullName
        }
        createdBy
        createdAt
        publishedAt
        status
      }
    }
  }
}

query articleChannelAll {
  channels: articleChannels {
    id
    icon
    name
    fullName
    path
    index
    level
    cover
    parent {
      id
    }
  }
}

query articleChannel($id: ID!) {
  channel: articleChannel(id: $id) {
    id
    icon
    name
    description
    cover
    path
    index
    level
    parent {
      id
    }
  }
}

mutation createArticle($input: ArticleCreateInput!) {
  article: createArticle(input: $input) {
    id
    title
    status
    channels {
      id
    }
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation updateArticle($id: ID!, $input: ArticleUpdateInput!) {
  article: updateArticle(id: $id, input: $input) {
    id
    title
    status
    channels {
      id
    }
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation deleteArticle($id: ID!) {
  deleteArticle(id: $id)
}

mutation deleteManyArticles($ids: [ID]!) {
  deleteManyArticles(ids: $ids)
}

query article($id: ID!) {
  article(id: $id) {
    id
    title
    status
    channels {
      id
    }
    content {
      id
      __typename
      ... on HtmlContent {
        text
      }
    }
  }
}

mutation createArticleChannel($input: ArticleChannelCreateInput!) {
  createArticleChannel(input: $input) {
    id
  }
}
