query myContacts {
  result: myContacts {
    id
    name
    groups {
      id
      name
      namespace
    }
  }
}

query orgContacts {
  result: orgContacts {
    id
    name
    namespaces {
      id
      name
    }
    groups {
      id
      name
      namespace
    }
  }
}

# """
# 通过 ID 查询通讯录
# """
query contacts($id: ID!, $group: ID!) {
  result: contacts(id: $id) {
    id
    name
    group(groupId: $group) {
      id
      name
      namespace
    }
    contacts(groupId: $group) {
      id
      name
      title
      sex
      avatar
    }
  }
}

query contact($id: ID!) {
  contact(id: $id) {
    id
    ...ContactParts
  }
}

fragment ContactParts on Contact {
  name
  title
  sex
  avatar
  phone {
    ...PhoneParts
  }
  email {
    ...EmailParts
  }
  address {
    ...AddressParts
  }
  phones {
    id
    primary
    label
    phone {
      ...PhoneParts
    }
  }
  emails {
    id
    primary
    label
    email {
      ...EmailParts
    }
  }
  addresses {
    id
    primary
    label
    address {
      ...AddressParts
    }
  }
}

fragment EmailParts on Email {
  status
  address
}

fragment PhoneParts on Phone {
  status
  number
}

fragment AddressParts on Address {
  country
  province
  city
  district
  street
  postalCode
}
