query projects {
  projects {
    total: totalCount
    current: currentPage
    pageSize
    edges {
      node {
        id
        logo
        name
        description
      }
    }
  }
}

query project($id: ID!) {
  project(id: $id) {
    id
    logo
    name
    description
  }
}
