mutation logout {
  logout
}

mutation loginByWeixin($clientId: String!, $authCode: String) {
  login(clientId: $clientId, loginType: WeChatPM, authCode: $authCode) {
    id
    name
    type
    token
    authorities
  }
}

# mutation loginByDingtalk($code: String!) {
#   login(loginType: dingtalk, authCode: $code) {
#     id
#     name
#     token
#     type
#     authoritys
#   }
# }

mutation loginByUsername(
  $clientId: String!
  $username: String
  $password: String
) {
  login(clientId: $clientId, username: $username, password: $password) {
    id
    name
    type
    token
    authorities
  }
}

query viewer {
  viewer {
    id
    type
    name
    title
    avatar
    phone
    email
    sex
    bio
    birthday
    company
    location
    account
    authorities
    imToken(platform: Web)
    # onlineStatus {
    #   status
    #   detailPlatformStatus {
    #     platform
    #     connection
    #     background
    #   }
    # }
    tenantId
  }
}

query currentTenant($clientId: ID!) {
  currentTenant(clientId: $clientId) {
    id
    domain
    licence {
      id
    }
    modules {
      id
      key
      name
      values
    }
  }
}
