query cloudDrive($id: ID!) {
  cloudDrive(id: $id) {
    id
    name
    type
    rootFolder
  }
}

mutation renameFile($id: ID!, $name: String!) {
  file: renameFile(id: $id, name: $name) {
    id
    name
    lastModified(format: "yyyy-MM-dd HH:mm")
  }
}

query cloudDrives {
  cloudDrives {
    id
    name
    type
    quota {
      id
      count
      usage
      size
      usageStr: usage(format: true)
      sizeStr: size(format: true)
    }
    rootFolder
  }
}

query file($id: ID!) {
  file(id: $id) {
    id
    name
    path
    size(format: true)
    mimeType
    extension
    isDirectory
    isRootFolder
    lastModified(format: "yyyy-MM-dd HH:mm")
    createdAt(format: "yyyy-MM-dd HH:mm")
    description
    parents {
      id
      isDirectory
      isRootFolder
      name
      path
    }
  }
}

query folder($folder: ID!) {
  currentFolder: file(id: $folder) {
    id
    name
    path
    isDirectory
    isRootFolder
    parents {
      id
      isDirectory
      isRootFolder
      name
      path
    }
  }
}

query listFiles($folder: ID!, $filter: FileFilter, $page: Int = 1, $orderBy: OrderBy) {
  listFiles(folder: $folder, filter: $filter, page: $page, pageSize: 30, orderBy: $orderBy) {
    pageSize
    currentPage
    totalPage
    totalCount
    edges {
      node {
        id
        name
        path
        size(format: true)
        mimeType
        extension
        isDirectory
        lastModified(format: "yyyy-MM-dd HH:mm")
      }
    }
  }
}
