query STORAGE {
  storage(id: "Global") {
    id
    name
    description
    type
    totalFiles
    usage(format: true)
    quota(format: true)
    createdAt(format: "YYYY-MM-dd")
  }
}
query listFiles($storage: ID!, $path: String) {
  currentFile: file(storage: $storage, path: $path) {
    id
    name
    path
    parents {
      id
      name
      path
    }
  }
  files: listFiles(storage: $storage, path: $path) {
    id
    name
    path
    size(format: true)
    mimeType
    isDirectory
    lastModified(format: "yyyy-MM-dd HH:mm")
  }
}
