query organization($id: ID!) {
  organization(id: $id) {
    ...OrganizationProfile
  }
}

mutation updateOrganizationProfile(
  $id: ID!
  $input: UpdateOrganizationProfileUpdateInput!
) {
  updateOrganizationProfile(id: $id, input: $input) {
    ...OrganizationProfile
  }
}

mutation renameOrganizationCode($id: ID!, $code: String!) {
  renameOrganizationCode(id: $id, code: $code) {
    ...OrganizationProfile
  }
}

fragment OrganizationProfile on Organization {
  id
  code
  name
  logo
  description
  email
  url
  location {
    province
    city
    district
    street
  }
}
