mutation moveMailboxMessageToFolder($id: ID!, $mailbox: ID!) {
  moveMailboxMessageToFolder(id: $id, mailbox: $mailbox) {
    id
    ...MailboxMessageFlagParts
  }
}

mutation updateMailboxMessageFlags($id: ID!, $flags: [String!]!, $mode: MailboxFlagsUpdateMode) {
  updateMailboxMessageFlags(id: $id, flags: $flags, mode: $mode) {
    id
    ...MailboxMessageFlagParts
  }
}

query mailboxMessage($id: ID!) {
  message: mailboxMessage(id: $id) {
    ...MailboxMessageParts
    ...MailboxMessageFlagParts
  }
}

query mailboxMessages($account: ID, $filter: MailboxMessageFilter) {
  mailboxMessages(account: $account, filter: $filter) {
    totalCount
    pageSize
    totalPage
    currentPage
    edges {
      node {
        ...MailboxMessageParts
        ...MailboxMessageFlagParts
      }
    }
  }
}

fragment MailboxMessageParts on MailboxMessage {
  id
  subject
  date
  sender {
    name
    domain
    localPart
    address
  }
  from {
    name
    localPart
    domain
    address
  }
  to {
    name
    localPart
    domain
    address
  }
  mimeType
  body
}

fragment MailboxMessageFlagParts on MailboxMessage {
  answered
  deleted
  draft
  flagged
  recent
  seen
}
