query screens {
  screens {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

query screen($id: ID!) {
  screen(id: $id) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

mutation updateScreen($id: ID!, $input: FactoryScreenUpdateInput!) {
  updateScreen(id: $id, input: $input) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

mutation createScreen($input: FactoryScreenCreateInput!) {
  createScreen(input: $input) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

mutation deleteScreen($id: ID!) {
  deleteScreen(id: $id) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

mutation validateAdminKey($key: String!) {
  validateAdminKey(key: $key)
}

query ping {
  ping
}

query getClientIp {
  getClientIp
}

query getScreenForIp($ip: String!) {
  getScreenForIp(ip: $ip) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}

subscription onUpdateScreen($id: ID) {
  onUpdateScreen(id: $id) {
    id
    info
    boundIp
    operator1
    operator2
    operator3
    status
    statusImage
    document1
    document2
    document3
    document4
    document5
    document6
    document7
    document8
    document9
    document10
    description
  }
}