name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run gql-gen && npm run build
        env:
          CI: true
          GRAPHQL_SCHEMA_URL: https://api.asany.cn/graphql
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Tag Name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            limaofeng/asany-admin:latest
            limaofeng/asany-admin:${{ env.RELEASE_VERSION }}

  github-release:
    needs: push_to_registry
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
